### Get products index
GET http://localhost:3000/products.json

### Get products show
GET http://localhost:3000/products/2.json

### Post products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "JanSport JS0A4QUE008",
  "price": 39,
  "image_url": "https://m.media-amazon.com/images/I/817EuMPlOOL._AC_SL1500_.jpg",
  "description": "JanSport JS0A4QUE008 Superbreak Plus Black"
}

### Patch products update
PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "price": 45
}

### Delete products destroy
DELETE http://localhost:3000/products/4.json