### Get products index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc3MzY4MTd9.jsjOIfFCwM68fKGGhobBx0M2mNCT-YSoA4dlZFWNNdw

### Get products show
GET http://localhost:3000/products/7.json

### Post products create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "JanSport JS0A4QUE00",
  "price": 40,
  "image_url": "https://m.media-amazon.com/images/I/817EuMPlOOL._AC_SL1500_.jpg",
  "description": "JanSport JS0A4QUE008 Superbreak Plus Black"
}

### Patch products update
PATCH http://localhost:3000/products/7.json
Content-Type: application/json

{
  "name": ""
}

### Delete products destroy
DELETE http://localhost:3000/products/17.json



### Get suppliers index
GET http://localhost:3000/suppliers.json

### Get suppliers show
GET http://localhost:3000/suppliers/3.json

### Post suppliers create
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "JanSport",
  "email": "jansport@example.com",
  "phone_number": "12345"
}

### Patch suppliers update
PATCH http://localhost:3000/suppliers/1.json
Content-Type: application/json

{
  "email": "sony@example.com"
}

### Delete suppliers destroy
DELETE http://localhost:3000/suppliers/6.json

### User create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jane",
  "email": "jane@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Session create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "password"
}

### Create order
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": 2,
  "product_id": 3,
  "quantity": 1,
  "subtotal": 50,
  "tax": 4.5,
  "total": 54.5
}

### Index orders
GET http://localhost:3000/orders.json


### Show order
GET http://localhost:3000/orders/1.json